animal/urls.py
from django.conf.urls import url

from . import views

app_name = 'animal'
urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^dynamic-required-1$', views.DynamicRequired1.as_view(),
        name='dynamic_required_1'),
    url(r'^dynamic-required-2$', views.DynamicRequired2.as_view(),
        name='dynamic_required_2'),
    url(r'^dynamic-required-3$', views.DynamicRequired3.as_view(),
        name='dynamic_required_3'),
    url(r'^dynamic-required-4$', views.DynamicRequired4.as_view(),
        name='dynamic_required_4'),
]

testform/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('animal.urls'))
]

animal/models.py
from django.db import models


class AnimalType(models.Model):
    code = models.CharField(primary_key=True, max_length=10)
    label = models.CharField(max_length=250)

    def __str__(self):
        return self.label


class Activity(models.Model):
    animal_type = models.ForeignKey(
        AnimalType, related_name="activities")
    label = models.CharField(max_length=200)

    def __str__(self):
        return self.label


class Animal(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField(null=True, blank=True)
    type = models.ForeignKey(AnimalType, related_name="animals")
    favorite_activity = models.ForeignKey(
        Activity, related_name="favored_by_animals")
    activities = models.ManyToManyField(
        Activity, related_name="animals", blank=True)
    internal_notes = models.TextField(blank=True, default="")

    def __str__(self):
        label = "{type}: {name} of age {age}. Favorite: {activity} "\
            "({count} activities)".format(
                type=self.type.label, name=self.name, age=self.age,
                activity=self.favorite_activity.label,
                count=self.activities.count())

        if self.internal_notes:
            label += " notes: {0}".format(self.internal_notes)

        return label

animal/views.py
import json

from django.shortcuts import render, redirect
from django.views.generic import View
from django.urls import reverse

from animal import forms
from animal.models import Animal, Activity, AnimalType


def get_menu_items():
    return [
        {
            "page_name": "home",
            "url": reverse("animal:home"),
            "title": "Model Form",
        }, {
            "page_name": "dynamic1",
            "url": reverse("animal:dynamic_required_1"),
            "title": "Dynamic Required 1",
        }, {
            "page_name": "dynamic2",
            "url": reverse("animal:dynamic_required_2"),
            "title": "Dynamic Required 2",
        }, {
            "page_name": "dynamic3",
            "url": reverse("animal:dynamic_required_3"),
            "title": "Dynamic Required 3",
        }, {
            "page_name": "dynamic4",
            "url": reverse("animal:dynamic_required_4"),
            "title": "Dynamic Required 4",
        },
    ]


class AnimalView(View):

    page_name = ""

    def __init__(self):
        super().__init__()
        self.context = {}
        self.context["page_name"] = self.page_name
        self.context["menu_items"] = get_menu_items()

    def _add_form_context(self, form):
        form_types = [
            {
                "value": choice[0],
                "label": choice[1]
            } for choice in form.fields["type"].choices
        ]
        form_activities = [
            {
                "value": choice[0],
                "label": choice[1]
            } for choice in form.fields["favorite_activity"].choices
        ]
        self.context.update({
            "form": form,
            "form_types_json": json.dumps(form_types),
            "form_activities_json": json.dumps(form_activities),
        })

    def dispatch(self, request, *args, **kwargs):
        activities = [
            {
                "value": activity.pk,
                "label": activity.label,
                "for_type": activity.animal_type.pk
            } for activity in Activity.objects.all()
        ]
        types = [
            {
                "value": type.pk,
                "label": type.label
            } for type in AnimalType.objects.all()
        ]
        types.insert(0, {
            "value": "",
            "label": "Select animal type"
        })
        self.context.update({
            "animals": Animal.objects.order_by("pk"),
            "activities_json": json.dumps(activities),
            "types_json": json.dumps(types),
        })
        return super().dispatch(request, *args, **kwargs)


class Home(AnimalView):

    page_name = "home"
    template_file = "animal/home.html"

    def get(self, request):
        self.context.update({
            "success": request.GET.get("success") == "success",
        })
        self._add_form_context(forms.Form1())
        return render(request, self.template_file, self.context)

    def post(self, request):
        form = forms.Form1(data=request.POST)
        if form.is_valid():
            form.save()
            url = reverse("animal:home") + "?success=success"
            return redirect(url)
        else:
            self.context.update({"success": False})
            self._add_form_context(form)
            return render(request, self.template_file, self.context)


class DynamicRequired1(AnimalView):

    page_name = "dynamic1"
    template_file = "animal/dynamic_required_1.html"

    def get(self, request):
        self.context.update({
            "success": request.GET.get("success") == "success",
        })
        self._add_form_context(forms.DynamicRequired1())
        return render(request, self.template_file, self.context)

    def post(self, request):
        form = forms.DynamicRequired1(data=request.POST)
        if form.is_valid():
            form.save()
            url = reverse("animal:dynamic_required_1") + "?success=success"
            return redirect(url)
        else:
            self.context.update({"success": False})
            self._add_form_context(form)
            return render(request, self.template_file, self.context)


class DynamicRequired2(AnimalView):

    page_name = "dynamic2"
    template_file = "animal/dynamic_required_2.html"

    def get(self, request):
        self.context.update({
            "success": request.GET.get("success") == "success",
        })
        self._add_form_context(forms.DynamicRequired2())
        return render(request, self.template_file, self.context)

    def post(self, request):
        form = forms.DynamicRequired2(data=request.POST)
        if form.is_valid():
            form.save()
            url = reverse("animal:dynamic_required_2") + "?success=success"
            return redirect(url)
        else:
            self.context.update({"success": False})
            self._add_form_context(form)
            return render(request, self.template_file, self.context)


class DynamicRequired3(AnimalView):

    page_name = "dynamic3"
    template_file = "animal/dynamic_required_3.html"

    def get(self, request):
        self.context.update({
            "success": request.GET.get("success") == "success",
        })
        self._add_form_context(forms.DynamicRequired3())
        self._add_age_choices()
        return render(request, self.template_file, self.context)

    def post(self, request):
        form = forms.DynamicRequired3(data=request.POST)
        if form.is_valid():
            form.save()
            url = reverse("animal:dynamic_required_3") + "?success=success"
            return redirect(url)
        else:
            self.context.update({"success": False})
            self._add_form_context(form)
            self._add_age_choices()
            return render(request, self.template_file, self.context)

    def _add_age_choices(self):
        form = self.context["form"]
        age_choices = [
            {
                "value": choice[0],
                "label": choice[1]
            } for choice in form.fields["age"].choices]
        self.context["form_age_json"] = json.dumps(age_choices)


class DynamicRequired4(AnimalView):

    page_name = "dynamic4"
    template_file = "animal/dynamic_required_4.html"

    def get(self, request):
        # animal = Animal.objects.order_by("-pk").first()
        # form = forms.DynamicRequired4(instance=animal)
        form = forms.DynamicRequired4()
        self.context.update({
            "success": request.GET.get("success") == "success",
            "form": form,
        })
        return render(request, self.template_file, self.context)

    def post(self, request):
        form = forms.DynamicRequired4(data=request.POST)
        if form.is_valid():
            # Notice the custom method!
            form.save_instance()
            url = reverse("animal:dynamic_required_4") + "?success=success"
            return redirect(url)
        else:
            self.context.update({
                "success": False,
                "form": form
            })
            return render(request, self.template_file, self.context)

animal/templates/animal/dynamic_required_1.html
{% extends "animal/root.html" %}

{% block title %}Form - Dynamic Required 1{% endblock %}
{% block page-title %}Form - Dynamic Required 1{% endblock %}
{% block content %}
    {% if success %}
        <div class="row">
            <div class="col-12">Success!</div>
        </div>
    {% endif %}
    <div id="app" class="row">
        <div class="col-12 col-md-10">
            <form method="post" v-cloak>
                {% csrf_token %}
                {% if form.errors %}
                    {{form.errors}}
                {% endif %}
                {% verbatim %}
                    <div class="form-group">
                        <label for="id_name">* Name</label>
                        <input v-model="name" required type="text" class="form-control" name="name" id="id_name">
                    </div>
                    <div class="form-group">
                        <label for="id_type">* Type</label>
                        <select v-model="type" required class="form-control" name="type" id="id_type">
                            <option v-for="option in formTypeChoices" :value="option.value">{{option.label}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_age"><span v-show="ageIsRequired">* </span>Age</label>
                        <input v-model="age" :required="ageIsRequired" type="number" class="form-control" name="age" id="id_age">
                    </div>
                    <div class="form-group">
                        <label for="id_favorite_activity">* Favorite Activity</label>
                        <select v-model="favoriteActivity" required class="form-control" name="favorite_activity" id="id_favorite_activity">
                            <option v-for="option in activityChoices" :value="option.value">{{option.label}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_activities">Activities</label>
                        <select v-model="activities" multiple class="form-control" name="activities" id="id_activities">
                            <option v-for="option in activityChoices" :value="option.value">{{option.label}}</option>
                        </select>
                    </div>
                {% endverbatim %}

                <button type="submit">Create animal</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block post-script %}
<script>
    var app = new Vue({
        el: '#app',
        computed: {
            ageIsRequired: function() {
                return this.type === 'cat';
            }
        },
        data: {
            name: '',
            type: '',
            age: null,
            favoriteActivity: '',
            activities: [],
            activityChoices: {{activities_json|safe}},
            typeChoices: {{types_json|safe}},
            formTypeChoices: {{form_types_json|safe}},
            formActivityChoices: {{form_activities_json|safe}},
        }
    });
</script>
{% endblock %}

animal/templates/animal/dynamic_required_2.html
{% extends "animal/root.html" %}

{% block title %}Form - Dynamic Required 2{% endblock %}
{% block page-title %}Form - Dynamic Required 2{% endblock %}
{% block content %}
    {% if success %}
        <div class="row">
            <div class="col-12">Success!</div>
        </div>
    {% endif %}
    <div id="app" class="row">
        <div class="col-12 col-md-10">
            <form method="post" v-cloak>
                {% csrf_token %}
                {% if form.errors %}
                    {{form.errors}}
                {% endif %}
                {% verbatim %}
                    <div class="form-group">
                        <label for="id_name">* Name</label>
                        <input v-model="name" required type="text" class="form-control" name="name" id="id_name">
                    </div>
                    <div class="form-group">
                        <label for="id_type">* Type</label>
                        <select v-model="type" required class="form-control" name="type" id="id_type">
                            <option v-for="option in formTypeChoices" :value="option.value">{{option.label}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_age"><span v-show="ageIsRequired">* </span>Age</label>
                        <input v-model="age" :required="ageIsRequired" type="number" class="form-control" name="age" id="id_age">
                    </div>
                    <div class="form-group">
                        <label for="id_favorite_activity">* Favorite Activity</label>
                        <select v-model="favoriteActivity" required class="form-control" name="favorite_activity" id="id_favorite_activity">
                            <option v-for="option in activityChoices" :value="option.value">{{option.label}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_activities">Activities</label>
                        <select v-model="activities" multiple class="form-control" name="activities" id="id_activities">
                            <option v-for="option in activityChoices" :value="option.value">{{option.label}}</option>
                        </select>
                    </div>
                {% endverbatim %}

                <button type="submit">Create animal</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block post-script %}
<script>
    var app = new Vue({
        el: '#app',
        computed: {
            ageIsRequired: function() {
                return this.type === 'cat';
            }
        },
        data: {
            name: '',
            type: '',
            age: null,
            favoriteActivity: '',
            activities: [],
            activityChoices: {{activities_json|safe}},
            typeChoices: {{types_json|safe}},
            formTypeChoices: {{form_types_json|safe}},
            formActivityChoices: {{form_activities_json|safe}},
        }
    });
</script>
{% endblock %}

animal/templates/animal/dynamic_required_3.html
{% extends "animal/root.html" %}

{% block title %}Form - Dynamic Required 3{% endblock %}
{% block page-title %}Form - Dynamic Required 3{% endblock %}
{% block content %}
    {% if success %}
        <div class="row">
            <div class="col-12">Success!</div>
        </div>
    {% endif %}
    <div id="app" class="row">
        <div class="col-12 col-md-10">
            <form method="post" v-cloak>
                {% csrf_token %}
                {% if form.errors %}
                    {{form.errors}}
                {% endif %}
                {% verbatim %}
                    <div class="form-group">
                        <label for="id_name">* Name</label>
                        <input v-model="name" required type="text" class="form-control" name="name" id="id_name">
                    </div>
                    <div class="form-group">
                        <label for="id_type">* Type</label>
                        <select v-model="type" required class="form-control" name="type" id="id_type">
                            <option v-for="option in formTypeChoices" :value="option.value">{{option.label}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_age">Age</label>
                        <select v-model="age" class="form-control" name="age" id="id_age">
                            <option v-for="option in formAgeChoices" :value="option.value">{{option.label}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_favorite_activity">* Favorite Activity</label>
                        <select v-model="favoriteActivity" required class="form-control" name="favorite_activity" id="id_favorite_activity">
                            <option v-for="option in availableActivities" :value="option.value">{{option.label}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_activities">Activities</label>
                        <select v-model="activities" multiple class="form-control" name="activities" id="id_activities">
                            <option v-for="option in availableActivities" :value="option.value">{{option.label}}</option>
                        </select>
                    </div>
                {% endverbatim %}

                <button type="submit">Create animal</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block post-script %}
<script>
    var DEFAULT_ACTIVITY = {
        value: '',
        label: 'Select an activity'
    };

    var app = new Vue({
        el: '#app',
        computed: {
            availableActivities: function() {
                if (!this.type) {
                    // Return default activity
                    return [DEFAULT_ACTIVITY];
                } else {
                    var activities = [DEFAULT_ACTIVITY];
                    for (var i=0; i < this.activityChoices.length; i++) {
                        var activity = this.activityChoices[i];
                        if (activity.for_type == this.type) {
                            activities.push(activity);
                        }
                    }
                    return activities;
                }
            },
        },
        data: {
            name: '',
            type: '',
            age: '',
            favoriteActivity: '',
            activities: [],
            activityChoices: {{activities_json|safe}},
            typeChoices: {{types_json|safe}},
            formTypeChoices: {{form_types_json|safe}},
            formActivityChoices: {{form_activities_json|safe}},
            formAgeChoices: {{form_age_json|safe}}
        }
    });
</script>
{% endblock %}

animal/templates/animal/dynamic_required_4.html
{% extends "animal/root.html" %}

{% block title %}Form - Dynamic Required 4{% endblock %}
{% block page-title %}Form - Dynamic Required 4{% endblock %}
{% block content %}
    {% if success %}
        <div class="row">
            <div class="col-12">Success!</div>
        </div>
    {% endif %}
    <div id="app" class="row">
        <div class="col-12 col-md-10">
            <form method="post">
                {% csrf_token %}
                {% if form.errors %}
                    {{form.errors}}
                {% endif %}
                {{ form.as_p }}
                <button type="submit">Create animal</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block post-script %}
{% endblock %}

animal/templates/animal/home.html
{% extends "animal/root.html" %}

{% block title %}Form - Model Form{% endblock %}
{% block page-title %}Form - Model Form{% endblock %}
{% block content %}
    {% if success %}
        <div class="row">
            <div class="col-12">Success!</div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create animal</button>
            </form>
        </div>
    </div>
{% endblock %}

animal/templates/animal/root.html
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static "animal/style.css" %}">
        <title>{% block title %}{% endblock %}</title>
        <style>
            [v-cloak] {
                display: none;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1>{% block page-title %}{% endblock %}</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <h2>Examples</h2>
                    <ul class="nav main-menu">
                        {% for item in menu_items %}
                            <li class="nav-item main-menu-item">
                                <a class="nav-link {% if item.page_name == page_name %}active{% endif %}" href="{{ item.url }}">{{ item.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h2>Form</h2>
                    {% block content %}{% endblock %}
                </div>
                <div class="col-md-6">
                    <h2>Animals</h2>
                    <ul>
                        {% for animal in animals %}
                            <li>{{animal}}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script></script></script></script>
        <script src="https://unpkg.com/vue"></script>
        {% block post-script %}
        {% endblock %}
    </body>
</html>